### ISSUE TITLE
EEXT-11 RT1064 Cannot Set BT_FUSE_SEL Fuse

### ISSUE THREAD

**Issue by docsteer** [JayHeng/NXP-MCUBootUtility#11]
We were attempting to use MCUBootUtility for production programming of fresh boards off the line. However we could not get the utility to set the BT_FUSE_SEL fuse. When attempting it I would try setting the fuse value to 1 but it would always get set back to zero and couldn't be saved. Eventually I was able to manually burn the fuse from the command line.

![image](https://user-images.githubusercontent.com/15143933/199252205-883e1ee9-0a4e-4100-b907-49a2261d477d.png)
![image](https://user-images.githubusercontent.com/15143933/199253245-06fd22cc-8de0-4301-9a2c-d75bddf6e7e1.png)

**Comment by JayHeng** [comment]
It works on my side. if you cannot set it by cfg1 view, you can input the value directly
