### ISSUE TITLE
EXT-14 RT105x Fail to ping Flashloader via UART

### ISSUE THREAD

**Issue by WenjieTan** [JayHeng/NXP-MCUBootUtility#112]
我用UART连接时，提示我更新flashlaoder.srec文件，改怎么解决？

**Comment by JayHeng** [comment]
您好，请提供更详细的信息，哪个芯片型号？FlexRAM有没有重新配置过？
你可以加到 恩智浦MCUBootUtility工具交流qq群里（群号：867386086），沟通可以更即时一些

**Comment by WenjieTan** [comment]
你好，我用的i.MXRT1052, 已经用USB-HID更新过程序。我想试试UART，结果出现这个问题。

**Comment by liliangego** [comment]
怎么解决的？我这边也是这个情况呀，这个flashlaoder.srec文件有最新的吗？

**Comment by JayHeng** [comment]
flashloader本身的问题，与Tool无关，因此关掉这个issue
