### ISSUE TITLE
EXT-16 Support for FlexSPI NOR download over JTAG/SWD using standard debugger

### ISSUE THREAD

**Issue by bigbrett** [JayHeng/NXP-MCUBootUtility#114]
I have an application image for MIMXRT1051CVL5B that I want to store in QSPI flash, but to execute from RAM after a POR. The reference manual states that this is possible, as the ROM bootloader can copy the image from flash into RAM and begin execution from RAM.  

This tool should support downloading the image into flash using commonly available debug adapters/flash programmers like SEGGER JLink or CMSIS-DAP. This is a much more common use case than via the serial port. 

If this is already possible and I missed the instructions, please let me know. Once an image is built, it should be able to be flashed using any third party flash tool, right?

**Comment by JayHeng** [comment]
I agree with you that debugger port is more common use than serial port, but my tool depends on NXP flashloader, the flashloader uses serial port to communicate with host.
