### ISSUE TITLE
EXT-17 Linux support

### ISSUE THREAD

**Issue by bigbrett** [JayHeng/NXP-MCUBootUtility#115]
Many companies are phasing out Windows (due to security concerns) and moving embedded development to Linux. This application is written in python, so should easily be portable to Linux host system. 

Please consider supporting Linux host OS for your next release.

**Comment by JayHeng** [comment]
My tool is designed for i.MXRT, i.MXRT belongs to MCU, Most of MCU developer (>95%) use Windows, that's why we only have Windows build

**Comment by JayHeng** [comment]
NXP will release new tool: MCUX secure provisioning, it includes linux support
