### ISSUE TITLE
EXT-19 RT1060 running too slow in non Xip mode

### ISSUE THREAD

**Issue by Marko625** [JayHeng/NXP-MCUBootUtility#125]
I was trying to get the device to work so that ROM loads entire code to RAM and it is run from there. I succeded using this tool but it ran to slow. Toggling pin signal was 10x slower then when I download code directly to RAM using debug interface.

I mannaged to fix this by setting entryPointAddress in .bd file to 0x2000 (0r 0x20002000 if trying to use DTCM) and using manualy MfgTool.

My question is why does MCUBootUtility set this to 0x2345 (0x20002345)? And how come it still works but slower than it should (but faster than XIP)?

**Comment by JayHeng** [comment]
The difference between debugging in RAM and booting from ROM is system environment:
When code is downloaded by Debugger, the system is clean as reset state
When code is booted by ROM, the system has been configured by ROM
Please double check system setting (mostly clock configuration) in your app, make sure it is aligned with ROM system setting
