### ISSUE TITLE
EXT-23 手动生成Efuse sb文件的烧录顺序问题

### ISSUE THREAD

**Issue by gyboy** [JayHeng/NXP-MCUBootUtility#144]
你好，Jay，有个问题要确认下，如果我需要手动生成eFuse相关的sb烧录文件（lock位，SRK，SW_GP2烧录数据等），我看到bd文件生成的配置的按照地址从小到大的（对比自动生成的lock位是靠后烧录），那么按照这个顺序烧录的话不是先lock了SW_GP2读写位再烧录数据，这样子SW_GP2不就无法烧录了么？

**Comment by JayHeng** [comment]
当前生成efuse sb文件并不会智能判断fuse本身逻辑顺序，可在下一版v2.2中改进。目前你可以将lock位烧录单独生成一个sb
