### ISSUE TITLE
EEXT-3 Rebuilding from source needs more explanation

### ISSUE THREAD

**Issue by richbria** [JayHeng/NXP-MCUBootUtility#3]
After installing python 2.7 I had to update pip using 
`python -m pip install --upgrade pip`
and then 
`pip.exe install PyInstaller==3.3.1`

before I could rebuild the application

**Comment by JayHeng** [comment]
yes, PyInstaller (4.1) is not compatible with Python 2.7, so setup script should force usage of PyInstaller 3.6 (or lower)
