### ISSUE TITLE
KBL-22 Port Setup界面Choice选项框有时显示异常

### ISSUE THREAD

**Issue by Jayson0626** [JayHeng/NXP-MCUBootUtility#32]
连接设备后软件偶尔会出现USB的枚举框显示异常问题。 
![22-1](https://user-images.githubusercontent.com/44720384/50343404-b3526980-0561-11e9-8330-da0f837c16c9.png)

**Comment by JayHeng** [comment]
It is wxPython UI stable issue, i don't want to fix it
