### ISSUE TITLE
EXT-9 End-user mode.

### ISSUE THREAD

**Issue by ripe909** [JayHeng/NXP-MCUBootUtility#59]
I would love to see a version/mode for end users performing field updates.  

This would be a very stripped down user interface which only allows selecting a firmware file and then initiating the all-in-one action.  All of the options and config would be hidden and preselected (based on JSON config file?) for the specific device they are updating.   

I started to look at doing this myself, but it may be something that others could benefit from as well.

![an11305_usb_in-system_programming_with_the_lpc11u3x_lpc11u2x_-_an11305v_1_pdf](https://user-images.githubusercontent.com/4607050/50976292-386fd500-14b5-11e9-87ba-ef36ec3b1f3c.png)

**Comment by JayHeng** [comment]
What is your NXPISP status? I will start to create this kind of version (called RT-Programmer) in next week

**Comment by ripe909** [comment]
Great news!   

For ISP I have a selection, J-Link, LPC-Link, and NXP-EVK OpenSDA, as well as a Beagle USB 480 for USB debugging if that helps.

**Comment by JayHeng** [comment]
The end-user mode version is done, v1.0.0 has been released
https://github.com/JayHeng/RT-Flash
