### ISSUE TITLE
EEXT-7 How to "Mass Erase" flash on RT1170-EVK to fix no SWD device found?

### ISSUE THREAD

**Issue by esutton** [JayHeng/NXP-MCUBootUtility#7]
My problem is understanding how to use MCU Boot Utility to "Mass Erase" flash on RT1170 in attempt to fix MCUXpresso to recover from SWD not being found. When I attempt to "mass Erase", I get "please configure boot device via Flashloader first" ?

- [RT1170 EVK MCUXpresso "SWD Configuration" 0 available SWD devices detected?](https://community.nxp.com/t5/i-MX-RT/RT1170-EVK-MCUXpresso-quot-SWD-Configuration-quot-0-available/m-p/1430765#M18824)

1) How do you  configure RT1170-EVK boot device via Flashloader?
2) After putting board SW1 into software downloader mode, do I connect a single USB cable J11?  
Or two USB cables, J11 and J20?  
I tried both J11 and J11 plus J20.

In SW1 downloader mode, with two USB cables connected, J11 and J20 connected, I see:
![image](https://user-images.githubusercontent.com/6115047/159069765-1a54368a-fe19-465e-9566-e8692a681662.png)

This is the MCUXpresso I am hoping to solve with MCU Boot Utility:

![image](https://user-images.githubusercontent.com/6115047/159070240-643238b2-03ba-44f5-b099-0b97baeb3956.png)

Thank you for a great tool and any advice,
-Ed

**Comment by JayHeng** [comment]
Click 'Connect to ROM' button first, then do 'Mass Erase'

**Comment by JayHeng** [comment]
J11 is CMSIS-DAP USB port, it is used for debugging.
J20 is BootROM USB SDP port, it is used for MCUBootUtility

**Comment by esutton** [comment]
@JayHeng thank you.  I was not using  'Connect to ROM' button first.

This worked to fix MCUXpresso from not detecting any SWD devices on my RT1170-EVK.

1) Power-off EVK, disconnect all USB cables
2) Set SW1 to serial mode: SW1: 1-OFF, 2-OFF, 3-OFF, 4-ON
3) Connect single USB cable from PC host to J20 USB1 (SDB)
4) With power cable J43 connected, switch on power SW5.
5) Launch NXP MCU Boot Utility, bin\NXP-MCUBootUtility.exe
6) Press button “Connect to ROM” on left
7) After “Connect to ROM”, verify USB-HID displays Vendor ID: 0x15A2, Product ID: 0x0073
8) Under Target Setup, select MCU Series and Device: i.MXRT1117x
9) Select tab Boot Device Memory
10) Change Start/Offset: 0x30000000 ( 8-digits) , Change Byte length 0x1000 (4-digits).
  - While not required, setting this helps you erase some flash memory, especially the FCB, IVT,BD area, which will influence the boot, then influence your debugger connection.
11) Press button Mass Erase
12) Restore SW1 to internal boot mode: SW1: 1-OFF, 2-OFF, 3-ON, 4-OFF, and reboot EVK board
